export * from 'taro-html-view'
export * from 'taro-design/components'

export { default as Page } from './page'
export { default as Tab } from './tab'
export { default as Header } from './header'
export { default as Image } from './image'
export { default as AuthLogin } from './auth'
export { default as RichTextPop } from './richText/pop'
export { default as UploadImage } from './upload/image'
export { default as Share } from './share'
export { default as Tabbar, useTabbarShow, useTabbarHide, useTabbarNumber, tabbar } from './tabbar'
export { default as Text } from './text'
export { default as ListLoading } from './list/loading'
export { default as Dropdown } from './dropdown'
export { ActionSheet } from './actionSheet'
export { Layout } from './layout'
